# Generated by Django 5.2.17 on 2026-09-28 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment_date', models.DateField()),
                ('kind', models.CharField(choices=[('new', 'New student'), ('re_enrolment', 'Re-enrolment'), ('transfer_in', 'Transfer from another school')], default='new', max_length=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('class_changed', 'Moved to another class'), ('withdrawn', 'Left the school'), ('completed', 'Year completed'), ('cancelled', 'Cancelled')], default='active', max_length=15)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=255)),
                ('transfer_to', models.CharField(blank=True, help_text='School the student left for.', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.academicyear')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.classgroup')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='schools.school')),
            ],
            options={
                'verbose_name': 'enrolment',
                'ordering': ['-academic_year__start_date', '-enrollment_date', '-id'],
            },
        ),
    ]
