# Generated by Django 5.2.17 on 2026-09-30 02:44

from django.db import migrations, models
from django.utils import timezone


def existing_accounts_are_confirmed(apps, schema_editor):
    """Accounts created before invitations required a confirmed email keep signing in as before."""
    apps.get_model("accounts", "User").objects.filter(email_verified_at__isnull=True).update(
        email_verified_at=timezone.now()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_finance_setup_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='invitation_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(existing_accounts_are_confirmed, migrations.RunPython.noop),
    ]
