# Generated by Django 5.2.17 on 2026-09-29 18:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('enrollments', '0002_initial'),
        ('people', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('registration', 'Registration'), ('tuition', 'Tuition'), ('exam', 'Exams'), ('transport', 'Transport'), ('canteen', 'Canteen'), ('uniform', 'Uniform'), ('supplies', 'Books and supplies'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='schools.school')),
            ],
            options={
                'verbose_name': 'fee category',
                'verbose_name_plural': 'fee categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FeeSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applies_to', models.CharField(choices=[('all', 'All students'), ('new', 'New students only'), ('returning', 'Returning students only')], default='all', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('installments', models.JSONField(default=list)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_schedules', to='academics.academicyear')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='finance.feecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_schedules', to='academics.level')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='schools.school')),
            ],
            options={
                'verbose_name': 'fee schedule',
                'ordering': ['academic_year', 'level__order', 'category__order', 'category__name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=30)),
                ('issue_date', models.DateField()),
                ('source', models.CharField(choices=[('enrolment', 'Enrolment fees'), ('manual', 'Manual')], default='manual', max_length=10)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('cancelled', 'Cancelled')], default='issued', max_length=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.CharField(blank=True, max_length=255)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='academics.academicyear')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='enrollments.enrollment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='people.student')),
            ],
            options={
                'verbose_name': 'invoice',
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('discount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_lines', to='finance.feecategory')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.invoice')),
            ],
            options={
                'verbose_name': 'invoice line',
                'ordering': ['invoice', 'due_date', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudentDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('percent', 'Percentage'), ('fixed', 'Fixed amount')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.CharField(choices=[('scholarship', 'Scholarship'), ('sibling', 'Sibling'), ('staff_child', 'Staff child'), ('hardship', 'Financial hardship'), ('other', 'Other')], default='other', max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='academics.academicyear')),
                ('category', models.ForeignKey(blank=True, help_text='Empty = every fee category (percentage discounts only).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='finance.feecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discounts', to='people.student')),
            ],
            options={
                'verbose_name': 'student discount',
                'ordering': ['-academic_year__start_date', 'student__last_name', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='feecategory',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='uniq_fee_category_name'),
        ),
        migrations.AddConstraint(
            model_name='feeschedule',
            constraint=models.UniqueConstraint(fields=('academic_year', 'level', 'category', 'applies_to'), name='uniq_fee_schedule'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['school', 'academic_year', 'status'], name='invoice_school_year_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['student', 'status'], name='invoice_student_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('school', 'number'), name='uniq_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='invoiceline',
            constraint=models.CheckConstraint(condition=models.Q(('discount__lte', models.F('amount'))), name='line_discount_le_amount'),
        ),
        migrations.AddConstraint(
            model_name='studentdiscount',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', False), ('is_active', True)), fields=('student', 'academic_year', 'category'), name='uniq_active_discount_per_category'),
        ),
        migrations.AddConstraint(
            model_name='studentdiscount',
            constraint=models.UniqueConstraint(condition=models.Q(('category__isnull', True), ('is_active', True)), fields=('student', 'academic_year'), name='uniq_active_discount_all_categories'),
        ),
        migrations.AddConstraint(
            model_name='studentdiscount',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', False), ('kind', 'fixed')), models.Q(('kind', 'percent'), ('value__lte', 100)), _connector='OR'), name='discount_kind_valid'),
        ),
    ]
