from pathlib import Path

from django.core.management.base import BaseCommand

from apps.accounts.permissions_registry import MODULES, SYSTEM_ROLES


class Command(BaseCommand):
    help = "Write the role × permission matrix (Markdown) for client review and sign-off."

    def add_arguments(self, parser):
        parser.add_argument("--output", help="File to write; prints to the console when omitted.")

    def handle(self, *args, **opts):
        roles = list(SYSTEM_ROLES.items())
        lines = [
            "# Permission matrix — built-in roles",
            "",
            "Generated by `python manage.py permission_matrix`. Source of truth: "
            "`backend/apps/accounts/permissions_registry.py`.",
            "Schools can adjust built-in roles or create their own in **Settings → Roles**; "
            "the Super Administrator always keeps every permission.",
            "",
            "| Module | Permission | " + " | ".join(spec["name"] for _, spec in roles) + " |",
            "|---|---|" + "---|" * len(roles),
        ]
        for _, label, perms in MODULES:
            for code, description in perms:
                marks = ["✔" if code in spec["permissions"] else "" for _, spec in roles]
                lines.append(f"| {label} | {description} (`{code}`) | " + " | ".join(marks) + " |")
        text = "\n".join(lines) + "\n"

        if opts["output"]:
            Path(opts["output"]).write_text(text, encoding="utf-8")
            self.stdout.write(self.style.SUCCESS(f"Wrote {opts['output']}"))
        else:
            self.stdout.write(text)
