# Generated by Django 5.2.17 on 2026-10-01 01:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('enrollments', '0002_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gradebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('missing_policy', models.CharField(choices=[('exclude', 'Leave missing marks out of the average'), ('zero', 'Count missing marks as zero')], default='exclude', max_length=10)),
                ('status', models.CharField(choices=[('open', 'In progress'), ('submitted', 'Submitted'), ('published', 'Published')], default='open', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('status_note', models.CharField(blank=True, help_text='Why the marks were sent back or reopened (latest).', max_length=255)),
                ('class_subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gradebooks', to='academics.classsubject')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='schools.school')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gradebooks', to='academics.term')),
            ],
            options={
                'verbose_name': 'gradebook',
                'ordering': ['term__order', 'class_subject__class_group__level__order', 'class_subject__subject__name'],
            },
        ),
        migrations.CreateModel(
            name='GradeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60)),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(choices=[('average', 'Average of the assessments'), ('total', 'Total of the points')], default='average', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('gradebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='assessments.gradebook')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='schools.school')),
            ],
            options={
                'verbose_name': 'grade category',
                'verbose_name_plural': 'grade categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('max_score', models.DecimalField(decimal_places=2, default=Decimal('20'), help_text='Marked out of this number.', max_digits=7, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='How much it counts inside its category (average method only).', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='schools.school')),
                ('gradebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='assessments.gradebook')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='assessments.gradecategory')),
            ],
            options={
                'verbose_name': 'assessment',
                'ordering': [models.OrderBy(models.F('date'), nulls_last=True), 'id'],
            },
        ),
        migrations.CreateModel(
            name='GradingScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('max_mark', models.DecimalField(decimal_places=2, default=Decimal('20'), help_text='Marks are reported out of this number, e.g. 20, 10 or 100.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('pass_mark', models.DecimalField(decimal_places=2, default=Decimal('10'), max_digits=5)),
                ('decimals', models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MaxValueValidator(3)])),
                ('rank_method', models.CharField(choices=[('competition', 'Ties share a rank and the next rank is skipped (1, 1, 3)'), ('dense', 'Ties share a rank and no rank is skipped (1, 1, 2)')], default='competition', max_length=12)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('level', models.OneToOneField(blank=True, help_text="Empty = the school's default scale.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grading_scale', to='academics.level')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='schools.school')),
            ],
            options={
                'verbose_name': 'grading scale',
                'ordering': ['level__order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('excused', models.BooleanField(default=False)),
                ('comment', models.CharField(blank=True, max_length=255)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='assessments.assessment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='enrollments.enrollment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='schools.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'grade',
                'ordering': ['assessment', 'enrollment'],
                'constraints': [models.UniqueConstraint(fields=('assessment', 'enrollment'), name='uniq_grade_per_assessment'), models.CheckConstraint(condition=models.Q(('excused', False), ('score__isnull', True), _connector='OR'), name='grade_excused_has_no_score'), models.CheckConstraint(condition=models.Q(('score__gte', 0), ('score__isnull', True), _connector='OR'), name='grade_not_negative')],
            },
        ),
        migrations.AddIndex(
            model_name='gradebook',
            index=models.Index(fields=['school', 'term', 'status'], name='gradebook_school_term_idx'),
        ),
        migrations.AddConstraint(
            model_name='gradebook',
            constraint=models.UniqueConstraint(fields=('class_subject', 'term'), name='uniq_gradebook_subject_term'),
        ),
        migrations.AddConstraint(
            model_name='gradecategory',
            constraint=models.UniqueConstraint(fields=('gradebook', 'name'), name='uniq_category_name'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.CheckConstraint(condition=models.Q(('max_score__gt', 0)), name='assessment_max_positive'),
        ),
        migrations.AddConstraint(
            model_name='gradingscale',
            constraint=models.UniqueConstraint(condition=models.Q(('level__isnull', True)), fields=('school',), name='uniq_school_default_scale'),
        ),
        migrations.AddConstraint(
            model_name='gradingscale',
            constraint=models.CheckConstraint(condition=models.Q(('pass_mark__lte', models.F('max_mark'))), name='scale_pass_within_max'),
        ),
        migrations.AddConstraint(
            model_name='gradingscale',
            constraint=models.CheckConstraint(condition=models.Q(('pass_mark__gte', 0)), name='scale_pass_not_negative'),
        ),
    ]
