# Generated by Django 5.2.17 on 2026-10-01 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('assessments', '0001_initial'),
        ('enrollments', '0002_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gradingscale',
            name='mentions',
            field=models.JSONField(blank=True, default=list, help_text='Honours bands, e.g. [{"min": 16, "label": "Très bien"}, {"min": 14, "label": "Bien"}].'),
        ),
        migrations.CreateModel(
            name='ReportComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(max_length=600)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_comments', to='enrollments.enrollment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='schools.school')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_comments', to='academics.term')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'report card comment',
                'constraints': [models.UniqueConstraint(condition=models.Q(('term__isnull', False)), fields=('enrollment', 'term'), name='uniq_report_comment_term'), models.UniqueConstraint(condition=models.Q(('term__isnull', True)), fields=('enrollment',), name='uniq_report_comment_year')],
            },
        ),
    ]
