# Generated by Django 5.2.17 on 2026-09-28 12:38

import apps.core.files
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner_type', models.CharField(choices=[('student', 'Student'), ('staff', 'Staff member'), ('school', 'School')], max_length=10)),
                ('owner_id', models.PositiveBigIntegerField()),
                ('category', models.CharField(choices=[('birth_certificate', 'Birth certificate'), ('id_photo', 'ID photo'), ('previous_report', 'Previous report card'), ('transfer_certificate', 'Transfer certificate'), ('medical', 'Medical record'), ('identity', 'Identity document'), ('diploma', 'Diploma / certificate'), ('contract', 'Contract'), ('official', 'Official document'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to=apps.core.files.SchoolUploadPath('documents'))),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='schools.school')),
            ],
            options={
                'verbose_name': 'document',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'owner_type', 'owner_id'], name='document_owner_idx')],
            },
        ),
    ]
