# Generated by Django 5.2.17 on 2026-10-01 02:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('enrollments', '0002_initial'),
        ('people', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registers', to='academics.classgroup')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='schools.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'class register',
                'ordering': ['-date', 'class_group__level__order', 'class_group__name'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused absence')], default='present', max_length=10)),
                ('minutes_late', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='enrollments.enrollment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='schools.school')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='attendance.classregister')),
            ],
            options={
                'verbose_name': 'attendance record',
                'ordering': ['register', 'enrollment'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused absence'), ('leave', 'On leave')], default='present', max_length=10)),
                ('minutes_late', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='schools.school')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='people.staffmember')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'staff attendance',
                'verbose_name_plural': 'staff attendance',
                'ordering': ['-date', 'staff__last_name', 'staff__first_name'],
            },
        ),
        migrations.AddIndex(
            model_name='classregister',
            index=models.Index(fields=['school', 'date'], name='register_school_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='classregister',
            constraint=models.UniqueConstraint(fields=('class_group', 'date'), name='uniq_register_class_date'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['enrollment', 'status'], name='record_enrollment_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('register', 'enrollment'), name='uniq_record_per_register'),
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'late'), ('minutes_late__isnull', True), _connector='OR'), name='record_minutes_only_when_late'),
        ),
        migrations.AddIndex(
            model_name='staffattendance',
            index=models.Index(fields=['school', 'date'], name='staff_att_school_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffattendance',
            constraint=models.UniqueConstraint(fields=('staff', 'date'), name='uniq_staff_attendance_day'),
        ),
        migrations.AddConstraint(
            model_name='staffattendance',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'late'), ('minutes_late__isnull', True), _connector='OR'), name='staff_minutes_only_when_late'),
        ),
    ]
