# Generated by Django 5.2.17 on 2026-09-28 11:34

import apps.schools.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.SlugField(max_length=30, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=60)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('logo', models.FileField(blank=True, upload_to=apps.schools.models.school_logo_path)),
                ('country', models.CharField(default='GN', max_length=2)),
                ('timezone', models.CharField(default='Africa/Conakry', max_length=50)),
                ('currency', models.CharField(default='GNF', max_length=3)),
                ('default_language', models.CharField(choices=[('fr', 'French'), ('en', 'English')], default='fr', max_length=2)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=20)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idle_timeout_minutes', models.PositiveSmallIntegerField(default=30)),
                ('student_number_prefix', models.CharField(default='STU', max_length=10)),
                ('employee_number_prefix', models.CharField(default='EMP', max_length=10)),
                ('invoice_prefix', models.CharField(default='INV', max_length=10)),
                ('receipt_prefix', models.CharField(default='REC', max_length=10)),
                ('ai_enabled', models.BooleanField(default=False)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='schools.school')),
            ],
            options={
                'verbose_name_plural': 'school settings',
            },
        ),
    ]
